### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by driskerr** [gbrlrudy/CodeAcademyProject#1]
Overall: very nice work!

You have a good eye for slide design! I love the background imagery for this project theme (especially the little bird on slide 2). My one critique on presentation design is that sometimes you have a lot of information on one slide (text, tables, graphs), it may be easier to interpret the information if you break it up across slides.

You accurately interpret the p-values and provide appropriate recommendations for conservation priorities.

There is a miscalculation of the correct sample size for the foot-and-mouth disease question. Although your input data was correct, the correct sample size is 510 (not 870). Please consult the sample size calculator (found [here](https://www.optimizely.com/sample-size-calculator/?conversion=15&effect=33.3&significance=90)). I appreciate that you went above and beyond to determine the number of weeks needed for observations in any park (not just Yellowstone).

Great job! Keep up the good work!

**Comment by gbrlrudy** [comment]
Thanks for the feedback!  Updated a new version of the pdf with the correct value.  It was displayed correctly on the chart for slide 4 but you were right, on slide 5 there was a typo that said the value was 870 instead of 510.

Thanks again!
